version: '3'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  redisCommander:
    image: tenstartups/redis-commander
    command: --redis-host redis
    links:
      - redis:redis
    ports:
      - '8081:8081'

volumes:
  redis-data:
    driver: local


# web:
#   # build: .
#   ports:
#    - "5000:5000"
#   volumes:
#    - .:/code
#   links:
#    - redis
# redis:
#   image: redis