# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define :maria do |node|
    node.vm.box = "ubuntu/trusty64"
    # node.vm.box = "ubuntu-16.04"
    node.vm.network :public_network     # ホストと同じNWに直接接続する
    config.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
    end
    config.vm.synced_folder "./vagrantdata", "/vagrant", create:true, owner: "root", group: "root", mount_options: ['dmode=777','fmode=666']
  end
end
