# - hosts: targets
#   tasks:
- name: install packages for setup of shell enviroments
  yum: name={{ item }} state=absent
  with_items: 
    - ibus-kkc
    - vlgothic-*
- name: set language conf
  become: yes
  become_method: sudo
  copy:
    dest: /etc/environment
    content: LC_ALL=ja_JP.UTF-8
